# : Manager [[[

[mgr]
cwd = { fg = "#f1dedc" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#fdbb41", bg = "#fdbb41" }
marker_cut      = { fg = "#fedfa6", bg = "#fedfa6" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#e0c38c", bg = "#e0c38c" }

# Count
count_copied   = { fg = "#261900", bg = "#fedfa6" }
count_cut      = { fg = "#261900", bg = "#fedfa6" }
count_selected = { fg = "#561e1a", bg = "#e0c38c" }

# Border
border_symbol = "‚îÇ"
border_style  = { fg = "#ffb4ab" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "‚ñà", close = "‚ñà" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#ffb4ab", bold = true, bg = "#1a1110" }
inactive  = { fg = "#e7bdb8", bg = "#1a1110" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#ffb4ab", fg = "#561e1a", bold = true }
normal_alt  = { bg = "#534341", fg = "#d8c2bf" }

# Select mode
select_main = { bg = "#e7bdb8", fg = "#442927", bold = true }
select_alt  = { bg = "#534341", fg = "#d8c2bf" }

# Unset mode
unset_main = { bg = "#e0c38c", fg = "#3f2e04", bold = true }
unset_alt  = { bg = "#534341", fg = "#d8c2bf" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "ü≠Å", close = "ü≠†" }
sep_right = { open = "ü≠Å", close = "ü≠†" }

# Permissions
perm_type  = { fg = "#c05346" }
perm_write = { fg = "#a67c2d" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#fca90f" }
perm_sep   = { fg = "#ff503d" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#ffb4ab", bg = "#423735" }
progress_error  = { fg = "#ffb4ab", bg = "#423735" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#423735" }
cand = { fg = "#ffb4ab" }
rest = { fg = "#561e1a" }
desc = { fg = "#f1dedc" }
separator = " ‚ñ∂ "
separator_style = { fg = "#f1dedc" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#e0c38c" }
title_warn  = { fg = "#ffb4ab" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#ffb4ab" }
active = { fg = "#e0c38c", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb4ab" }
value  = { fg = "#f1dedc" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#ffb4ab", bg = "#561e1a" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#ffb4ab" }
title   = {}
hovered = { fg = "#fedfa6", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#f1dedc" }
run    = { fg = "#f1dedc" }
footer = { fg = "#442927", bg = "#e7bdb8" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#f1dedc" },
    { name = "*/", fg = "#ffb4ab" },
]

# : ]]]
