# : Manager [[[

[mgr]
cwd = { fg = "#e1e2e8" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#ca74ff", bg = "#ca74ff" }
marker_cut      = { fg = "#f1daff", bg = "#f1daff" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#d6bee5", bg = "#d6bee5" }

# Count
count_copied   = { fg = "#241432", bg = "#f1daff" }
count_cut      = { fg = "#241432", bg = "#f1daff" }
count_selected = { fg = "#003257", bg = "#d6bee5" }

# Border
border_symbol = "‚îÇ"
border_style  = { fg = "#9fcafc" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "‚ñà", close = "‚ñà" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#9fcafc", bold = true, bg = "#101418" }
inactive  = { fg = "#bac8db", bg = "#101418" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#9fcafc", fg = "#003257", bold = true }
normal_alt  = { bg = "#42474e", fg = "#c2c7cf" }

# Select mode
select_main = { bg = "#bac8db", fg = "#253140", bold = true }
select_alt  = { bg = "#42474e", fg = "#c2c7cf" }

# Unset mode
unset_main = { bg = "#d6bee5", fg = "#3a2948", bold = true }
unset_alt  = { bg = "#42474e", fg = "#c2c7cf" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "ü≠Å", close = "ü≠†" }
sep_right = { open = "ü≠Å", close = "ü≠†" }

# Permissions
perm_type  = { fg = "#5678a6" }
perm_write = { fg = "#9151b9" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#b741ff" }
perm_sep   = { fg = "#378cff" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#9fcafc", bg = "#36393e" }
progress_error  = { fg = "#ffb4ab", bg = "#36393e" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#36393e" }
cand = { fg = "#9fcafc" }
rest = { fg = "#003257" }
desc = { fg = "#e1e2e8" }
separator = " ‚ñ∂ "
separator_style = { fg = "#e1e2e8" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#d6bee5" }
title_warn  = { fg = "#9fcafc" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#9fcafc" }
active = { fg = "#d6bee5", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#9fcafc" }
value  = { fg = "#e1e2e8" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#9fcafc", bg = "#003257" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#9fcafc" }
title   = {}
hovered = { fg = "#f1daff", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#e1e2e8" }
run    = { fg = "#e1e2e8" }
footer = { fg = "#253140", bg = "#bac8db" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e1e2e8" },
    { name = "*/", fg = "#9fcafc" },
]

# : ]]]
