[mgr]
ratio = [2,3,3]
sort_by = "natural"
sort_sensitive = true
linemode = "size"
show_hidden = true
show_symlink = true


[preview]
wrap = "yes"
image_delay = 100
image_filter = "nearest"
image_quality = 50


[opener]
edit = [
  { run = "nvim %s", block = true},
]

play = [
  { run = "mpv %s", orphan = true},
]

open = [
  { run = "xdg-open %s" , desc = "Open"},
]

[open]
rules = [
	{ mime = "text/*", use = "edit" },
	{ mime = "video/*", use = "play" },

	{ url = "*.html", use = [ "open", "edit" ] },
]


[input]
cursor_blink = true







